package libproject.db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


public class SearchData extends javax.swing.JFrame {

    /**
     * Creates new form Java_jtable_data
     */
	
	public SearchData() {}
	public String cond;
    public void SearchData(String data) {
        initComponents();
        cond=data;
        System.out.println(data);
    }

    //Show_Jtable_row_data_temp jtRowData = new Show_Jtable_row_data_temp();
    
    UpdateMember jtRowData = new UpdateMember();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
    	Connection conn = null;
 	   Statement stmt = null;
 	   ResultSet rs;
 	  String[] columnNames = {"First Name", "Middle Name", "Last Name", 
 			 "Work Address", "Work City", "Work State", "Work Zip",
 			 "Home Address", "Home City", "Home State", "Home Zip",
 			 "Work Area Code", "Work Number", "Home Area Code", "Home Number",
 			 "Cell Area Code", "Cell Number", "Contact id", "Work address id",
 			 "Home address id", "Work phone id", "Home phone id", "Cell phone id", 
 			 "Birth date id", "anniversary id",
 			 "Birth Date", "Anniversary", "temp"};

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        DefaultTableModel model = new DefaultTableModel();
		   model.setColumnIdentifiers(columnNames);
		   
		   
        
        try{
		      
		      Class.forName("com.mysql.jdbc.Driver");

		      System.out.println("Connecting to database...");
		      conn = DriverManager.getConnection("jdbc:mysql://localhost/library?autoReconnect=true&useSSL=false","root","");
		      
		      stmt=conn.createStatement();
		      
		      String sql = "select first_name as FirstName, ifnull(middle_name,'') as MiddleName, ifnull(last_name,'') as LastName, \n" + 
		      		"ifnull(w.address,'') as WorkAddress, ifnull(w.city,'') as Workcity, ifnull(w.state,'') as WorkState, ifnull(w.zip,'') as WorkZip,\n" + 
		      		"ifnull(h.address,'') as HomeAddress, ifnull(h.city,'') as Homecity, ifnull(h.state,'') as HomeState, ifnull(h.zip,'') as HomeZip,\n" + 
		      		"ifnull(wp.area_code,'') as WorkAreaCode, ifnull(wp.Number,'') as WorkNumber, ifnull(hp.area_code,'') as HomeAreaCode, ifnull(hp.Number,'') as HomeNumber,\n" + 
		      		"ifnull(cp.area_code,'') as CellAreaCode, ifnull(cp.Number,'') as CellNumber, \n" + 
		      		"c.contact_id as cid, ifnull(w.address_id,'0') as waid, ifnull(h.address_id,'0') as haid, \n"
		      		+ "ifnull(wp.phone_id,'0') as wpid, ifnull(hp.phone_id,'0') as hpid, ifnull(cp.phone_id,'0') as cpid, \n"
		      		+ "ifnull(b.date_id,'0') as bdid, ifnull(a.date_id,'0') as adid,"
		      		+ "ifnull(b.date,'1900-01-01') as BirthDate, ifnull(a.date,'1900-01-01') as Anniversary \n" +
		      		"from contact c Inner join address w \n" + 
		      		"on c.contact_id=w.contact_id and w.address_type='Work address'\n" + 
		      		"left join address h\n" + 
		      		"on c.contact_id=h.contact_id and h.address_type='Home address'\n" + 
		      		"left join phone wp\n" + 
		      		"On c.contact_id=wp.contact_id and wp.phone_type='Work phone'\n" + 
		      		"left join phone hp \n" + 
		      		"On c.contact_id=hp.contact_id and hp.phone_type='Home phone'\n" + 
		      		"Left join phone cp \n" + 
		      		"On c.contact_id=cp.contact_id and cp.phone_type='Cell phone' "
		      		+ "Left join date b On c.contact_id=b.contact_id and b.date_type='Birth Date'\n" + 
		      		"Left join date a On c.contact_id=a.contact_id and a.date_type='Anniversary'"
		      		+ "where first_name like '%"+cond+"%'"
		      				+ "Or middle_name like '%" +cond+ "%' \n" + 
		      				"Or last_name like '%" +cond+ "%' \n" + 
		      				"Or w.address like '%" +cond+ "%' \n" + 
		      				"Or w.city like '%" +cond+ "%' \n" + 
		      				"Or w.state like '%" +cond+ "%' \n" + 
		      				"Or h.address like '%" +cond+ "%' \n" + 
		      				"Or h.city like '%" +cond+ "%' \n" + 
		      				"Or h.state like '%" +cond+ "%' \n" + 
		      				"Or wp.area_code like '%" +cond+ "%' \n" + 
		      				"Or wp.number like '%" +cond+ "%' \n" + 
		      				"Or hp.area_code like '%" +cond+ "%' \n" + 
		      				"Or hp.number like '%" +cond+ "%' \n" + 
		      				"Or cp.area_code like '%" +cond+ "%' \n" + 
		      				"Or cp.number like '%" +cond+ "%' \n" + 
		      				"Or b.date like '%" +cond+ "%' \n" + 
		      				"Or a.date like '%" +cond+ "%' \n" + 
		      				"Order by first_name, middle_name, last_name, w.address, w.state, w.city, h.address, h.state, h.city;";
		      System.out.println(sql);
		      
			  rs = stmt.executeQuery(sql);
			  
			  while (rs.next()) {

				  
				  System.out.println(rs.getString(1)+rs.getString(2));
				   
				   String fname = rs.getString(1) ;
				   String mname = rs.getString(2) ;
				   String lname = rs.getString(3) ;
				   String wadd = rs.getString(4);
				   String wcity = rs.getString(5);
				   String wstate = rs.getString(6);
				   String wzip = rs.getString(7);
				   String hadd = rs.getString(8);
				   String hcity = rs.getString(9);
				   String hstate = rs.getString(10);
				   String hzip = rs.getString(11);
				   String warea = rs.getString(12);
				   String wnum = rs.getString(13);
				   String harea = rs.getString(14);
				   String hnum = rs.getString(15);
				   String carea = rs.getString(16);
				   String cnum = rs.getString(17);
				   String cid = rs.getString(18);
				   String waid = rs.getString(19);
				   String haid = rs.getString(20);
				   String wpid = rs.getString(21);
				   String hpid = rs.getString(22);
				   String cpid = rs.getString(23);
				   String bdid = rs.getString(24);
				   String adid = rs.getString(25);
				   String bdate = rs.getString(26);
				   String adate = rs.getString(27);
				   
				   model.addRow(new Object[]{fname,mname,lname,wadd,wcity,wstate,wzip,hadd,hcity,hstate,hzip,
						   warea,wnum,harea,hnum,carea,cnum,cid,waid,haid,wpid,hpid,cpid,bdid,adid,bdate,adate});
				   jTable1.setModel(model);
				   //model.setModel(new javax.swing.table.DefaultTableModel(new Object[]{fname,mname,lname}));
				   
				   jTable1.getColumnModel().getColumn(17).setMinWidth(0);
				   jTable1.getColumnModel().getColumn(17).setMaxWidth(0);
				   jTable1.getColumnModel().getColumn(17).setWidth(0);
				   
				   jTable1.getColumnModel().getColumn(18).setMinWidth(0);
				   jTable1.getColumnModel().getColumn(18).setMaxWidth(0);
				   jTable1.getColumnModel().getColumn(18).setWidth(0);
				   
				   jTable1.getColumnModel().getColumn(19).setMinWidth(0);
				   jTable1.getColumnModel().getColumn(19).setMaxWidth(0);
				   jTable1.getColumnModel().getColumn(19).setWidth(0);
				   
				   jTable1.getColumnModel().getColumn(20).setMinWidth(0);
				   jTable1.getColumnModel().getColumn(20).setMaxWidth(0);
				   jTable1.getColumnModel().getColumn(20).setWidth(0);
				   
				   jTable1.getColumnModel().getColumn(21).setMinWidth(0);
				   jTable1.getColumnModel().getColumn(21).setMaxWidth(0);
				   jTable1.getColumnModel().getColumn(21).setWidth(0);
				   
				   jTable1.getColumnModel().getColumn(22).setMinWidth(0);
				   jTable1.getColumnModel().getColumn(22).setMaxWidth(0);
				   jTable1.getColumnModel().getColumn(22).setWidth(0);
				   
				   jTable1.getColumnModel().getColumn(23).setMinWidth(0);
				   jTable1.getColumnModel().getColumn(23).setMaxWidth(0);
				   jTable1.getColumnModel().getColumn(23).setWidth(0);
				   
				   jTable1.getColumnModel().getColumn(24).setMinWidth(0);
				   jTable1.getColumnModel().getColumn(24).setMaxWidth(0);
				   jTable1.getColumnModel().getColumn(24).setWidth(0);
				   
				   
			  }

		      
	   } catch(Exception e) {
	   System.out.println("Error:"+e);
	   }
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        int index = jTable1.getSelectedRow();
        
        TableModel model = jTable1.getModel();
        
           String fname = model.getValueAt(index, 0).toString();
		   String mname = model.getValueAt(index, 1).toString();
		   String lname = model.getValueAt(index, 2).toString();
		   String wadd = model.getValueAt(index, 3).toString();
		   String wcity = model.getValueAt(index, 4).toString();
		   String wstate = model.getValueAt(index, 5).toString();
		   String wzip = model.getValueAt(index, 6).toString();
		   String hadd = model.getValueAt(index, 7).toString();
		   String hcity = model.getValueAt(index, 8).toString();
		   String hstate = model.getValueAt(index, 9).toString();
		   String hzip = model.getValueAt(index, 10).toString();
		   String warea = model.getValueAt(index, 11).toString();
		   String wnum = model.getValueAt(index, 12).toString();
		   String harea = model.getValueAt(index, 13).toString();
		   String hnum = model.getValueAt(index, 14).toString();
		   String carea = model.getValueAt(index, 15).toString();
		   String cnum = model.getValueAt(index, 16).toString();
		   String cid = model.getValueAt(index, 17).toString();
		   String waid = model.getValueAt(index, 18).toString();
		   String haid = model.getValueAt(index, 19).toString();
		   String wpid = model.getValueAt(index, 20).toString();
		   String hpid = model.getValueAt(index, 21).toString();
		   String cpid = model.getValueAt(index, 22).toString();
		   String bdid = model.getValueAt(index, 23).toString();
		   String adid = model.getValueAt(index, 24).toString();
		   String bdate = model.getValueAt(index, 25).toString();
		   String adate = model.getValueAt(index, 26).toString();
		   
		   System.out.println(fname+mname+lname+wadd+wcity+wstate+wzip+hadd+hcity+hstate+hzip+
						   warea+wnum+harea+hnum+carea+cnum+cid+waid+haid+wpid+hpid+cpid+bdid+adid+bdate+adate);
        
		this.setVisible(false);
        jtRowData.setVisible(true);
        jtRowData.pack();
        jtRowData.setLocationRelativeTo(null);
        jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        jtRowData.jT1.setText(fname);
        jtRowData.jT2.setText(mname);
        jtRowData.jT3.setText(lname);
        jtRowData.jT4.setText(wadd);
        jtRowData.jT5.setText(wcity);
        jtRowData.jT6.setText(wstate);
        jtRowData.jT7.setText(wzip);
        jtRowData.jT8.setText(hadd);
        jtRowData.jT9.setText(hcity);
        jtRowData.jT10.setText(hstate);
        jtRowData.jT11.setText(hzip);
        jtRowData.jT12.setText(warea);
        jtRowData.jT13.setText(wnum);
        jtRowData.jT14.setText(harea);
        jtRowData.jT15.setText(hnum);
        jtRowData.jT16.setText(carea);
        jtRowData.jT17.setText(cnum);
        jtRowData.jT18.setText(cid);
        jtRowData.jT19.setText(waid);
        jtRowData.jT20.setText(haid);
        jtRowData.jT21.setText(wpid);
        jtRowData.jT22.setText(hpid);
        jtRowData.jT23.setText(cpid);
        jtRowData.jT24.setText(bdid);
        jtRowData.jT25.setText(adid);
        jtRowData.jT26.setText(bdate);
        jtRowData.jT27.setText(adate);
        
    }                                    

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration                   
}
